In [ ]:
Numpy-> Numerical Python-> Play around numbers
Pandas-> Dataframe(Rows and columns)->dataframe Manipulation
Matplotlib-> Data Visualization
Seaborn-> Data Visualization
Plotly-> Data Visualization
Scikitlearn->sklearn-> Preprocessing and ml algorithm
Scipy->Scientific python->Statistical fn

In [1]:
import numpy as np

In [2]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [7]:
np.arange(10,1,-2)

array([10,  8,  6,  4,  2])

In [8]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
np.zeros(10,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [10]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [11]:
np.ones(10,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [13]:
np.linspace(0,2,5)

array([0. , 0.5, 1. , 1.5, 2. ])

In [14]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
np.random.rand(3,4) #uniform didtribution

array([[0.95108126, 0.12442965, 0.89087826, 0.94936832],
       [0.9716373 , 0.52752043, 0.91393277, 0.93493913],
       [0.44459075, 0.73426199, 0.6667469 , 0.96756658]])

In [17]:
np.random.randn(3,4) #normal distribution

array([[ 1.27960767,  1.70481026, -0.40199077, -0.07066384],
       [-0.75012592,  1.24430294, -0.19537152, -0.94595611],
       [-0.59044162,  0.12416245, -0.51448878,  0.66722246]])

In [18]:
np.random.randint(1,10)

1

In [19]:
np.random.randint(1,10,100)

array([9, 8, 2, 3, 6, 7, 5, 2, 1, 8, 2, 1, 3, 7, 4, 8, 1, 7, 5, 2, 9, 9,
       9, 4, 3, 4, 1, 8, 5, 4, 7, 3, 8, 6, 8, 3, 5, 5, 1, 1, 4, 3, 2, 4,
       4, 3, 4, 4, 6, 9, 8, 7, 1, 2, 3, 4, 6, 8, 7, 6, 3, 6, 2, 5, 6, 7,
       9, 1, 1, 4, 9, 1, 6, 5, 2, 2, 1, 7, 5, 4, 5, 4, 3, 4, 1, 4, 7, 8,
       4, 5, 2, 3, 4, 9, 7, 3, 2, 3, 6, 7])

In [20]:
sample_array=np.arange(30)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [23]:
sample_array.reshape(2,15)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [24]:
sample_array.reshape(7,5)

ValueError: cannot reshape array of size 30 into shape (7,5)

In [25]:
sample_array.max()

29

In [26]:
sample_array.min()

0

In [27]:
sample_array.mean()

14.5

In [28]:
sample_array.argmax()

29

In [29]:
sample_array.argmin()

0

In [31]:
a=np.random.rand(3,4)

In [32]:
a

array([[0.62180721, 0.70494628, 0.52495001, 0.74043213],
       [0.88471301, 0.11706498, 0.50082516, 0.26651201],
       [0.19947302, 0.57723344, 0.2990291 , 0.81073119]])

In [33]:
a.T

array([[0.62180721, 0.88471301, 0.19947302],
       [0.70494628, 0.11706498, 0.57723344],
       [0.52495001, 0.50082516, 0.2990291 ],
       [0.74043213, 0.26651201, 0.81073119]])

In [34]:
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [35]:
sample_array[2]

2

In [36]:
sample_array[3:8]

array([3, 4, 5, 6, 7])

In [37]:
sample_array[0]=100
sample_array

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29])

In [40]:
sample_matrix=np.array([[1,4,5,21],[17,32,31,25],[52,32,16,14]])

In [42]:
sample_matrix

array([[ 1,  4,  5, 21],
       [17, 32, 31, 25],
       [52, 32, 16, 14]])

In [43]:
sample_matrix[1,2]

31

In [44]:
sample_matrix[0,3]

21

In [45]:
sample_matrix[1,:]

array([17, 32, 31, 25])

In [46]:
sample_matrix[1]

array([17, 32, 31, 25])

In [47]:
sample_matrix[:,(2,0)]

array([[ 5,  1],
       [31, 17],
       [16, 52]])

In [48]:
sample_array

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29])

In [49]:
sample_array+sample_array

array([200,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58])

In [50]:
np.mean(sample_array)

17.833333333333332

In [51]:
np.std(sample_array)

17.33413459686472

In [52]:
np.median(sample_array)

15.5

In [53]:
np.var(sample_array)

300.47222222222234

In [54]:
np.exp(sample_array)

array([2.68811714e+43, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06,
       8.88611052e+06, 2.41549528e+07, 6.56599691e+07, 1.78482301e+08,
       4.85165195e+08, 1.31881573e+09, 3.58491285e+09, 9.74480345e+09,
       2.64891221e+10, 7.20048993e+10, 1.95729609e+11, 5.32048241e+11,
       1.44625706e+12, 3.93133430e+12])

In [55]:
np.log(sample_array)

array([4.60517019, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509, 2.39789527, 2.48490665, 2.56494936, 2.63905733,
       2.7080502 , 2.77258872, 2.83321334, 2.89037176, 2.94443898,
       2.99573227, 3.04452244, 3.09104245, 3.13549422, 3.17805383,
       3.21887582, 3.25809654, 3.29583687, 3.33220451, 3.36729583])

In [57]:
np.square(sample_array)

array([10000,     1,     4,     9,    16,    25,    36,    49,    64,
          81,   100,   121,   144,   169,   196,   225,   256,   289,
         324,   361,   400,   441,   484,   529,   576,   625,   676,
         729,   784,   841])

In [58]:
np.sqrt(sample_array)

array([10.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766,  3.31662479,  3.46410162,  3.60555128,  3.74165739,
        3.87298335,  4.        ,  4.12310563,  4.24264069,  4.35889894,
        4.47213595,  4.58257569,  4.69041576,  4.79583152,  4.89897949,
        5.        ,  5.09901951,  5.19615242,  5.29150262,  5.38516481])

In [59]:
np.argmax(sample_array)

0

In [60]:
array=np.random.rand(3,4)
array

array([[0.9099446 , 0.88995058, 0.59202211, 0.33996433],
       [0.16192477, 0.20130116, 0.2509979 , 0.65537206],
       [0.83751627, 0.35247673, 0.00836862, 0.02689592]])

In [64]:
np.round(array,2)

array([[0.91, 0.89, 0.59, 0.34],
       [0.16, 0.2 , 0.25, 0.66],
       [0.84, 0.35, 0.01, 0.03]])

In [66]:
sports=np.array(['golf','cricket','football','basketball','golf'])
sports

array(['golf', 'cricket', 'football', 'basketball', 'golf'], dtype='<U10')

In [67]:
np.unique(sports)

array(['basketball', 'cricket', 'football', 'golf'], dtype='<U10')

In [68]:
import pandas as pd

In [70]:
sports1=pd.Series([1,2,3,4],index=["cricket","football","golf","basketball"])
sports1

cricket       1
football      2
golf          3
basketball    4
dtype: int64

In [74]:
sports2=pd.Series([11,2,3,4,3],index=["cricket","fball","golf","basketball","hockey"])
sports2

cricket       11
fball          2
golf           3
basketball     4
hockey         3
dtype: int64

In [75]:
sports1+sports2

basketball     8.0
cricket       12.0
fball          NaN
football       NaN
golf           6.0
hockey         NaN
dtype: float64